name: webrtc-chat
networks:
  webrtc-chat:
    name: "webrtc-chat"
    driver: bridge
    enable_ipv4: false
    enable_ipv6: true
services:
  stun:
    container_name: webrtc-stun
    image: webrtc-stun:latest
    pull_policy: never
    networks:
      - "webrtc-chat"
  server:
    container_name: webrtc-server
    hostname: webrtc-server
    image: webrtc-server:latest
    pull_policy: never
    networks:
      - "webrtc-chat"
  web:
    container_name: webrtc-web
    hostname: ${MAIN_HOSTNAME}
    image: webrtc-chat:latest
    pull_policy: never
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    networks:
      - "webrtc-chat"
