name: local-webrtc-chat
networks:
  local-webrtc-chat:
    name: "local-webrtc-chat"
    driver: bridge
    enable_ipv4: false
    enable_ipv6: true
    ipam:
      config:
        - subnet: ${RFC5375_RANDOMIZED_ULA}
volumes:
  static:
    local-webrtc-chat-static:
      name: "local-webrtc-chat-static"
services:
  web:
    container_name: local-webrtc-chat
    image: nginx:latest
    pull_policy: always
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "local-webrtc-chat-static:/usr/share/nginx/html:ro"
    networks:
      - "local-webrtc-chat"
