networks:
  dn42-webrtc-chat:
    name: "dn42-webrtc-chat"
    driver: bridge
    enable_ipv4: false
    enable_ipv6: true
    ipam:
      config:
        - subnet: ${RFC5375_RANDOMIZED_ULA}
volumes:
  chat_acme_challenge:
    name: chat_acme_challenge
  chat_acme_certs:
    name: chat_acme_certs
services:
  web:
    container_name: dn42-webrtc-chat
    image: nginx:latest
    pull_policy: always
    volumes:
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "chat_acme_challenge:/usr/share/nginx/acme-challenge"
      - "chat_acme_certs:/etc/nginx/acme-certs:ro"
      - "./out:/usr/share/nginx/html:ro"
    networks:
      - "dn42-webrtc-chat"
