name: dn42-webrtc-chat
networks:
  dn42-webrtc-chat:
    name: "dn42-webrtc-chat"
    driver: bridge
    enable_ipv4: false
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fdda:8ca4:1556:a007::/64"
          gateway: "fdda:8ca4:1556:a007:ffff::1"
services:
  web:
    container_name: dn42-webrtc-chat
    image: docker.io/library/caddy:latest
    pull_policy: always
    networks:
      dn42-webrtc-chat:
        ipv6_address: "fdda:8ca4:1556:a007::1"
    volumes:
      - "./caddy.json:/caddy.json:ro"
    command:
      - "caddy"
      - "run"
      - "--config=/caddy.json"
