services:
  coturn:
    image: mycoturn:latest
    pull_policy: never
    restart: unless-stopped
    container_name: coturn-dn42
    networks:
      - dn42-coturn-net
    env_file: .env
    volumes:
      - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    cap_add:
      - NET_ADMIN
    user: root
    command:
      - "--log-file=stdout"

networks:
  dn42-coturn-net:
    name: "dn42-coturn-net"
    driver: bridge
    enable_ipv4: false
    enable_ipv6: true
    ipam:
      config:
        - subnet: ${RFC5375_RANDOMIZED_ULA}
